
'use server';

/**
 * @fileOverview A flow for translating multiple pieces of text content in a single batch.
 *
 * - translatePageContent - A function that translates an array of text content to a target language.
 */

import { ai } from '@/ai/genkit';
import {
  TranslatePageContentInput,
  TranslatePageContentOutput,
  TranslatePageContentInputSchema,
  TranslatePageContentOutputSchema,
} from './translate-page-content.schemas';

// A simple dictionary for dummy translations
const translationsDb: Record<string, Record<string, string>> = {
  hindi: {
    // Get Started Page
    'AI Crop Recommendation for Farmers': 'किसानों के लिए एआई फसल सिफारिश',
    'Get Started': 'शुरू हो जाओ',
    'Translate Page...': 'पेज का अनुवाद करें...',

    // Login Page
    'Back to Get Started': 'शुरुआत पर वापस जाएं',
    'Welcome to CropNavi': 'क्रॉपनवी में आपका स्वागत है',
    'Sign in to continue to your dashboard.': 'अपने डैशबोर्ड पर जाने के लिए साइन इन करें।',
    'Or continue with': 'या इसके साथ जारी रखें',
    'Email': 'ईमेल',
    'Password': 'पासवर्ड',
    'Forgot your password?': 'क्या आप अपना पासवर्ड भूल गए?',
    'Sign In': 'साइन इन करें',
    "Don't have an account?": 'क्या आपका खाता नहीं है?',
    'Sign up': 'साइन अप करें',
    "By continuing, you agree to CropNavi's": 'जारी रखकर, आप क्रॉपनवी की',
    'Terms of Service': 'सेवा की शर्तें',
    'and': 'और',
    'Privacy Policy': 'गोपनीयता नीति',

    // Dashboard & Sidebar
    'Welcome, Farmer!': 'किसान, आपका स्वागत है!',
    'Here are the tools to help you grow smarter.': 'यहां वे उपकरण हैं जो आपको बेहतर ढंग से विकसित होने में मदद करेंगे।',
    'AI Crop Recommendation': 'एआई फसल सिफारिश',
    'Get AI-driven crop suggestions based on your soil and climate.': ' अपनी मिट्टी और जलवायु के आधार पर एआई-संचालित फसल सुझाव प्राप्त करें।',
    'AI Disease Detection': 'एआई रोग पहचान',
    'Upload a photo to diagnose plant diseases instantly.': 'पौधों की बीमारियों का तुरंत निदान करने के लिए एक फोटो अपलोड करें।',
    'Market Analysis': 'बाजार विश्लेषण',
    'Analyze market trends and prices for your crops.': ' अपनी फसलों के लिए बाजार के रुझान और कीमतों का विश्लेषण करें।',
    'Sustainability Score': 'संवहनीयता स्कोर',
    'Calculate and improve your farm’s sustainability rating.': 'अपने खेत की संवहनीयता रेटिंग की गणना करें और सुधार करें।',
    'Community Forum': 'सामुदायिक मंच',
    'Connect with other farmers, ask questions, and share knowledge.': 'अन्य किसानों से जुड़ें, प्रश्न पूछें और ज्ञान साझा करें।',
    'Achievements': 'उपलब्धियां',
    'Track your progress and earn badges for your farming skills.': ' अपनी प्रगति को ट्रैक करें और अपने कृषि कौशल के लिए बैज अर्जित करें।',
    'Dashboard': 'डैशबोर्ड',
    'Crop Recommendation': 'फसल सिफारिश',
    'Disease Detection': 'रोग पहचान',
    'Educational Modules': 'शैक्षिक मॉड्यूल',
    'Point of Sale': 'बिक्री केंद्र',
    'Products': 'उत्पाद',
    'Sales History': 'बिक्री इतिहास',

    // Crop Rec Page
    'Enter coordinates manually or use your GPS to fetch soil data. Then, describe your farm, and our AI will suggest the best crops for you.': 'मिट्टी का डेटा प्राप्त करने के लिए निर्देशांक मैन्युअल रूप से दर्ज करें या अपने जीपीएस का उपयोग करें। फिर, अपने खेत का वर्णन करें, और हमारा एआई आपके लिए सर्वोत्तम फसलों का सुझाव देगा।',
    '1. Location for Soil Analysis': '1. मिट्टी विश्लेषण के लिए स्थान',
    'Latitude (e.g., 23.610)': 'अक्षांश (जैसे, 23.610)',
    'Longitude (e.g., 85.279)': 'देशांतर (जैसे, 85.279)',
    'Fetch Data for Coordinates': 'निर्देशांक के लिए डेटा प्राप्त करें',
    'Detect My Location & Fetch Data': 'मेरा स्थान पहचानें और डेटा प्राप्त करें',
    'The AI will use the fetched soil data as its primary source for recommendations.': 'एआई सिफारिशों के लिए अपने प्राथमिक स्रोत के रूप में प्राप्त मिट्टी के डेटा का उपयोग करेगा।',
    '2. Farm & Climate Details': '2. खेत और जलवायु विवरण',
    'Annual Rainfall': 'वार्षिक वर्षा',
    'Primary Soil Type': 'प्राथमिक मिट्टी का प्रकार',
    'Primary Goal': 'प्राथमिक लक्ष्य',
    'Risk Tolerance': 'जोखिम सहनशीलता',
    'Field Size': 'खेत का आकार',
    'Total Budget (₹)': 'कुल बजट (₹)',
    'Total Budget (e.g., 50000)': 'कुल बजट (जैसे, 50000)',
    'Fertilizer Preference': 'उर्वरक वरीयता',
    'Irrigation Method': 'सिंचाई विधि',
    'Crop History': 'फसल इतिहास',
    'Most Recent Crop': 'सबसे हालिया फसल',
    'Harvest Year': 'फसल का साल',
    'What was the most recent crop grown on this field?': 'इस खेत में उगाई गई सबसे हालिया फसल कौन सी थी?',
    'Recommend Crops': 'फसलों की सिफारिश करें',
    'AI-Powered Recommendations': 'एआई-संचालित सिफारिशें',
    'Based on your input, here are our top suggestions.': 'आपके इनपुट के आधार पर, यहां हमारे शीर्ष सुझाव दिए गए हैं।',
    'SoilGrids Data Preview': 'सॉइलग्रिड्स डेटा पूर्वावलोकन',
    "This is the scientific soil data fetched from SoilGrids.org for your location. Review the data and visual maps. Click 'Use This Data' when done.": "यह आपके स्थान के लिए SoilGrids.org से प्राप्त वैज्ञानिक मिट्टी डेटा है। डेटा और विज़ुअल मानचित्रों की समीक्षा करें। हो जाने पर 'इस डेटा का उपयोग करें' पर क्लिक करें।",
    'Table Data': 'तालिका डेटा',
    'Interactive Map': 'इंटरैक्टिव मानचित्र',
    'Raw Data': 'कच्चा डेटा',
    'View on Google Maps': 'Google मानचित्र पर देखें',
    'Use This Data': 'इस डेटा का उपयोग करें',
    'Cancel': 'रद्द करना',
    'Our AI is analyzing your farm data...': 'हमारा एआई आपके खेत के डेटा का विश्लेषण कर रहा है...',
    'Recommended Crops': 'अनुशंसित फसलें',
    'Reasoning': 'तर्क',
    'Your Recommendations Await': 'आपकी सिफारिशें प्रतीक्षित हैं',
    'totalBudgetPlaceholder': 'जैसे, 50000',
    'latitudePlaceholder': 'अक्षांश (जैसे, 23.610)',
    'longitudePlaceholder': 'देशांतर (जैसे, 85.279)',
    'fertilizerPrefLabel': 'उर्वरक वरीयता',
    'irrigationMethodLabel': 'सिंचाई विधि',
    'harvestYearLabel': 'फसल का साल',
    'resultTitle': 'एआई-संचालित सिफारिशें',
    'resultDescription': 'आपके इनपुट के आधार पर, यहां हमारे शीर्ष सुझाव दिए गए हैं।',
    'soilDialogTitle': 'सॉइलग्रिड्स डेटा पूर्वावलोकन',
    'soilDialogDescription': "यह आपके स्थान के लिए SoilGrids.org से प्राप्त वैज्ञानिक मिट्टी डेटा है। डेटा और विज़ुअल मानचित्रों की समीक्षा करें। हो जाने पर 'इस डेटा का उपयोग करें' पर क्लिक करें।",
    'tableTab': 'तालिका डेटा',
    'mapsTab': 'इंटरैक्टिव मानचित्र',
    'rawTab': 'कच्चा डेटा',
    'googleMapsButton': 'Google मानचित्र पर देखें',
    'useDataButton': 'इस डेटा का उपयोग करें',
    'cancelButton': 'रद्द करना',
    'placeholderDescription': 'हमारा एआई आपके खेत के डेटा का विश्लेषण कर रहा है...',
    'recommendedCropsLabel': 'अनुशंसित फसलें',
    'reasoningLabel': 'तर्क',
    'placeholderTitle': 'आपकी सिफारिशें प्रतीक्षित हैं',
    'farmDetailsLabel': 'खेत और जलवायु विवरण',
    'annualRainfallLabel': 'वार्षिक वर्षा',
    'soilTypeLabel': 'प्राथमिक मिट्टी का प्रकार',
    'primaryGoalLabel': 'प्राथमिक लक्ष्य',
    'riskToleranceLabel': 'जोखिम सहनशीलता',
    'fieldSizeLabel': 'खेत का आकार',
    'totalBudgetLabel': 'कुल बजट (₹)',
    'recentCropLabel': 'सबसे हालिया फसल',
    'cropHistoryDescription': 'इस खेत में उगाई गई सबसे हालिया फसल कौन सी थी?',
    'locationDescription': 'एआई सिफारिशों के लिए अपने प्राथमिक स्रोत के रूप में प्राप्त मिट्टी के डेटा का उपयोग करेगा।',
    'detectLocationButton': 'मेरा स्थान पहचानें और डेटा प्राप्त करें',
    'fetchCoordsButton': 'निर्देशांक के लिए डेटा प्राप्त करें',
    'locationLabel': 'मिट्टी विश्लेषण के लिए स्थान',
    'description': 'मिट्टी का डेटा प्राप्त करने के लिए निर्देशांक मैन्युअल रूप से दर्ज करें या अपने जीपीएस का उपयोग करें। फिर, अपने खेत का वर्णन करें, और हमारा एआई आपके लिए सर्वोत्तम फसलों का सुझाव देगा।',
    'title': 'एआई फसल सिफारिश',
    'cropHistoryLabel': 'फसल इतिहास',

    // Disease Detection

    "Use your camera or upload a photo of an affected plant leaf to get an AI-powered diagnosis.": "एआई-संचालित निदान प्राप्त करने के लिए अपने कैमरे का उपयोग करें या प्रभावित पौधे की पत्ती की तस्वीर अपलोड करें।",
    "Live Camera": "लाइव कैमरा",
    "Upload File": "फाइल अपलोड करें",
    "Camera Access Required": "कैमरा एक्सेस आवश्यक है",
    "Please allow camera access in your browser settings to use this feature.": "इस सुविधा का उपयोग करने के लिए कृपया अपनी ब्राउज़र सेटिंग्स में कैमरा एक्सेस की अनुमति दें।",
    "Capture & Diagnose": "कैप्चर और निदान करें",
    "Plant Photo": "पौधे की तस्वीर",
    "Upload a clear image of the affected plant part. Max 5MB.": "प्रभावित पौधे के हिस्से की एक स्पष्ट छवि अपलोड करें। अधिकतम 5MB।",
    "Diagnose": "निदान",
    "Image to Analyze": "विश्लेषण के लिए छवि",
    "Scanning for diseases...": "बीमारियों के लिए स्कैनिंग...",
    "Diagnosis Result": "निदान परिणाम",
    "Confidence": "आत्मविश्वास",
    "Description & Treatment": "विवरण और उपचार",
    "Looks Healthy!": "स्वस्थ लग रहा है!",
    "No significant disease was detected in the image.": "छवि में कोई महत्वपूर्ण बीमारी का पता नहीं चला।",
    "Use your camera or upload an image and your diagnosis will appear here.": "अपने कैमरे का उपयोग करें या एक छवि अपलोड करें और आपका निदान यहां दिखाई देगा।",

    // Market Analysis
    "Market Price Visualization": "बाजार मूल्य विज़ुअलाइज़ेशन",
    "Select filters to see live price trends from Agmarknet for a crop in your market.": "अपने बाजार में फसल के लिए एगमार्कनेट से लाइव मूल्य रुझान देखने के लिए फ़िल्टर चुनें।",
    "Select Commodity": "कमोडिटी चुनें",
    "Select State": "राज्य चुनें",
    "Select District": "जिला चुनें",
    "Enter Market Name": "बाजार का नाम दर्ज करें",
    "From Date": "से तिथि",
    "To Date": "तिथि तक",
    "Clear All Filters": "सभी फ़िल्टर साफ़ करें",
    "Using Sample Data": "नमूना डेटा का उपयोग करना",
    "Live data from Agmarknet is currently unavailable. Displaying sample data instead.": "एगमार्कनेट से लाइव डेटा वर्तमान में अनुपलब्ध है। इसके बजाय नमूना डेटा प्रदर्शित हो रहा है।",
    "Could Not Fetch Data": "डेटा प्राप्त नहीं किया जा सका",
    "No market data found for this crop/region.": "इस फसल/क्षेत्र के लिए कोई बाजार डेटा नहीं मिला।",
    "Please select filters to view price data from Agmarknet.": "एगमार्कनेट से मूल्य डेटा देखने के लिए कृपया फ़िल्टर चुनें।",
    "Generate Market & Profit Analysis": "बाजार और लाभ विश्लेषण उत्पन्न करें",
    "Filter for market data above, then add your costs to get an AI-powered financial summary.": "ऊपर बाजार डेटा के लिए फ़िल्टर करें, फिर एआई-संचालित वित्तीय सारांश प्राप्त करने के लिए अपनी लागत जोड़ें।",
    "Market Data (per Ton)": "बाजार डेटा (प्रति टन)",
    "This will be auto-filled with data from the chart above. You can also paste your own.": "यह ऊपर दिए गए चार्ट से डेटा के साथ स्वतः भर जाएगा। आप अपना खुद का भी पेस्ट कर सकते हैं।",
    "Your Expenditures": "आपके व्यय",
    "e.g., Seeds: ₹2000, Fertilizer: ₹3500, Labor: ₹5000": "जैसे, बीज: ₹2000, उर्वरक: ₹3500, श्रम: ₹5000",
    "Analyze Now": "अभी विश्लेषण करें",
    "Generating analysis...": "विश्लेषण उत्पन्न हो रहा है...",
    "AI-Generated Analysis": "एआई-जनित विश्लेषण",
    "Market Summary": "बाजार सारांश",
    "Profit & Loss Analysis": "लाभ और हानि विश्लेषण",
    "Your market analysis and profit/loss summary will appear here.": "आपका बाजार विश्लेषण और लाभ/हानि सारांश यहां दिखाई देगा।",
    "Using Dummy Data": "डमी डेटा का उपयोग करना",
    "Live API keys for Agmarknet are not configured. Displaying dummy data instead.": "एगमार्कनेट के लिए लाइव एपीआई कुंजी कॉन्फ़िगर नहीं हैं। इसके बजाय डमी डेटा प्रदर्शित हो रहा है।",

    // Sustainability Score
    "Provide details about your farm to get an AI-calculated sustainability rating.": "एआई-गणना वाली स्थिरता रेटिंग प्राप्त करने के लिए अपने खेत के बारे में विवरण प्रदान करें।",
    "Soil Health": "मृदा स्वास्थ्य",
    "Nitrogen (kg/ha)": "नाइट्रोजन (किग्रा/हेक्टेयर)",
    "Phosphorus (kg/ha)": "फास्फोरस (किग्रा/हेक्टेयर)",
    "Potassium (kg/ha)": "पोटेशियम (किग्रा/हेक्टेयर)",
    "Soil pH": "मिट्टी का पीएच",
    "Moisture (%)": "नमी (%)",
    "Farming Practices": "खेती के तरीके",
    "Irrigation": "सिंचाई",
    "Tillage": "जुताई",
    "Pesticides": "कीटनाशक",
    "Crop History & Rotation": "फसल इतिहास और रोटेशन",
    "Describe your rotation for the last 2-3 seasons.": "पिछले 2-3 मौसमों के लिए अपने रोटेशन का वर्णन करें।",
    "Market & Financials": "बाजार और वित्तीय",
    "Describe price trends and your costs.": "मूल्य प्रवृत्तियों और अपनी लागतों का वर्णन करें।",
    "Calculate Score": "स्कोर की गणना करें",
    "Calculating your score...": "आपके स्कोर की गणना हो रही है...",
    "Your Sustainability Score": "आपका स्थिरता स्कोर",
    "out of 100": "100 में से",
    "Rationale & Recommendations": "तर्क और सिफारिशें",
    "Your sustainability score and insights will appear here.": "आपका स्थिरता स्कोर और अंतर्दृष्टि यहां दिखाई देगी।",

    // Community Forum
    "Connect with farmers, share, and learn.": "किसानों से जुड़ें, साझा करें और सीखें।",
    "Start New Discussion": "नई चर्चा शुरू करें",
    "replies": "जवाब",
    "likes": "पसंद",
    "Back to Forum": "फोरम पर वापस",
    "Posted by": "द्वारा पोस्ट किया गया",
    "Like": "पसंद",
    "Replies": "जवाब",
    "Share": "शेयर करें",
    "Post a Reply": "एक उत्तर पोस्ट करें",
    "Write your reply here...": "अपना जवाब यहां लिखें...",
    "Submit Reply": "उत्तर जमा करें",

    // Profile
    "Farmer": "किसान",
    "Edit Profile": "प्रोफ़ाइल संपादित करें",
    "Save Changes": "बदलाव सहेजें",
    "Enter interests separated by commas.": "अल्पविराम से अलग करके रुचियां दर्ज करें।",

    // Achievements
    "Track your progress, earn badges, and become a top farmer!": "अपनी प्रगति को ट्रैक करें, बैज अर्जित करें, और एक शीर्ष किसान बनें!",
    "My Badges": "मेरे बैज",
    "Work in Progress": "कार्य प्रगति पर है",
    "Leaderboard": "लीडरबोर्ड",
    "Rank": "पद",
    "Score": "स्कोर",
    "Keep up the great work!": "बहुत अच्छा काम करते रहें!",
    "Top 5 farmers by Sustainability Score": "स्थिरता स्कोर के अनुसार शीर्ष 5 किसान",

    // Placeholders
    "This feature is coming soon! Get ready to earn badges and showcase your farming skills.": "यह सुविधा जल्द ही आ रही है! बैज अर्जित करने और अपने कृषि कौशल का प्रदर्शन करने के लिए तैयार हो जाइए।",
    "Our library of tutorials, guides, and quizzes is being curated. Check back soon to expand your farming knowledge.": "हमारे ट्यूटोरियल, गाइड और क्विज़ की लाइब्रेरी क्यूरेट की जा रही है। अपने कृषि ज्ञान का विस्तार करने के लिए जल्द ही वापस देखें।",

    // Chatbot
    "Chat with AI": "एआई के साथ बातचीत",
    "CropNavi Assistant": "क्रॉपनवी असिस्टेंट",
    "Online": "ऑनलाइन",
    "Hello! I'm the CropNavi Assistant. How can I help you today?": "नमस्ते! मैं क्रॉपनवी असिस्टेंट हूं। मैं आज आपकी कैसे मदद कर सकता हूं?",
    "Ask a question...": "एक सवाल पूछें...",

    // Weather Card
    "Weather Intelligence": "मौसम खुफिया",
    "Current Temperature": "वर्तमान तापमान",
    "Humidity": "नमी",
    "Wind": "हवा",
    "Rainfall": "वर्षा",
    "Now": "अब",
    "Last 7 Days": "पिछले 7 दिन",
    "Last 30 Days": "पिछले 30 दिन",
    "Last 6 Months": "पिछले 6 महीने",
    "Last Year": "पिछले साल",
    "Min": "न्यूनतम",
    "Max": "अधिकतम",
    "Avg": "औसत",
    "Rain": "वर्षा",
    "weatherDescription": "कोयंबटूर, तमिलनाडु",
    "Your Location": "आपकी जगह",
    "mapOverlayLabel": "नक्शा परत",
    "overlayNone": "कोई नहीं",
    "overlayPh": "पीएच (पानी)",
    "overlayClay": "मिट्टी की सामग्री",
    "overlayNitrogen": "नाइट्रोजन",
    "overlaySoc": "मिट्टी कार्बनिक कार्बन",
    "overlaySand": "रेत सामग्री",
    "overlaySilt": "गाद सामग्री",

    // POS & Products
    'Search products...': 'उत्पाद खोजें...',
    'Add': 'जोड़ें',
    'Cart': 'गाड़ी',
    'Customer Name (optional)': 'ग्राहक का नाम (वैकल्पिक)',
    'Remove': 'हटाएं',
    'Total': 'कुल',
    'Process Sale': 'बिक्री प्रक्रिया',
    'Stock': 'स्टॉक',
    'Insufficient stock': 'अपर्याप्त स्टॉक',
    'Cart is empty': 'गाड़ी खाली है',
    'Sale processed successfully': 'बिक्री सफल रही',
    'Failed to fetch products': 'उत्पादों को लाने में विफल',
    'Failed to process sale': 'बिक्री संसाधित करने में विफल',
    'Product Management': 'उत्पाद प्रबंधन',
    'Edit Product': 'उत्पाद संपादित करें',
    'Add New Product': 'नया उत्पाद जोड़ें',
    'Product Name': 'उत्पाद का नाम',
    'Description': 'विवरण',
    'Price': 'कीमत',
    'Stock Quantity': 'स्टॉक मात्रा',
    'Select Category': 'श्रेणी चुनें',
    'Update': 'अपडेट करें',
    'Create': 'बनाएं',
    'Edit': 'संपादित करें',
    'Delete': 'हटाएं',
    'Failed to fetch categories': 'श्रेणियां लाने में विफल',
    'Product updated successfully': 'उत्पाद अद्यतन सफल',
    'Product created successfully': 'उत्पाद निर्माण सफल',
    'Failed to save product': 'उत्पाद सहेजने में विफल',
    'Are you sure you want to delete this product?': 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?',
    'Product deleted successfully': 'उत्पाद सफलतापूर्वक हटाया गया',
    'Failed to delete product': 'उत्पाद हटाने में विफल',

    // Sales
    'Search sales...': 'बिक्री खोजें...',
    'Sale #': 'बिक्री #',
    'No notes': 'कोई नोट नहीं',
    'items': 'आइटम',
    'Sale Details': 'बिक्री विवरण',
    'Date': 'तारीख',
    'Notes': 'नोट्स',
    'Items': 'आइटम',
    'Select a sale to view details': 'विवरण देखने के लिए बिक्री चुनें',
    'Failed to fetch sales': 'बिक्री लाने में विफल',
    'None': 'कोई नहीं',
    'All': 'सभी',
    'Receipt': 'रसीद',
    'Sale Complete': 'बिक्री पूरी हुई',
    'Subtotal': 'उप-योग',
    'Close': 'बंद करें',
    'Clear Cart': 'कार्ट साफ़ करें',
    'Transaction ID': 'लेन-देन आईडी',
    'Stock Limit': 'स्टॉक सीमा',
    'Actions': 'क्रियाएं',
    'View Details': 'विवरण देखें',
    'Manage sales and inventory efficiently': 'बिक्री और इन्वेंट्री को कुशलता से प्रबंधित करें',
    'No products found': 'कोई उत्पाद नहीं मिला',
  },
  tamil: {
    // Get Started Page
    'AI Crop Recommendation for Farmers': 'விவசாயிகளுக்கான செயற்கை நுண்ணறிவு பயிர் பரிந்துரை',
    'Get Started': 'தொடங்குங்கள்',
    'Translate Page...': 'பக்கத்தை மொழிபெயர்க்கவும்...',

    // Login Page
    'Back to Get Started': 'முகப்புக்குத் திரும்பு',
    'Welcome to CropNavi': 'CropNavi-க்கு வரவேற்கிறோம்',
    'Sign in to continue to your dashboard.': 'உங்கள் டாஷ்போர்டுக்குச் செல்ல உள்நுழையவும்.',
    'Or continue with': 'அல்லது இதனுடன் தொடரவும்',
    'Email': 'மின்னஞ்சல்',
    'Password': 'கடவுச்சொல்',
    'Forgot your password?': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'Sign In': 'உள்நுழைய',
    "Don't have an account?": 'கணக்கு இல்லையா?',
    'Sign up': 'பதிவு செய்யவும்',
    "By continuing, you agree to CropNavi's": 'தொடர்வதன் மூலம், CropNavi-யின்',
    'Terms of Service': 'சேவை விதிமுறைகள்',
    'and': 'மற்றும்',
    'Privacy Policy': 'தனியுரிமைக் கொள்கை',

    // Dashboard & Sidebar
    'Welcome, Farmer!': 'வரவேற்கிறோம் விவசாயி!',
    'Here are the tools to help you grow smarter.': 'நீங்கள் சிறப்பாக விவசாயம் செய்ய உதவும் கருவிகள் இங்கே உள்ளன.',
    'AI Crop Recommendation': 'AI பயிர் பரிந்துரை',
    'Get AI-driven crop suggestions based on your soil and climate.': 'உங்கள் மண் மற்றும் காலநிலைக்கு ஏற்ப AI-மூலம் பயிர் பரிந்துரைகளைப் பெறுங்கள்.',
    'AI Disease Detection': 'AI நோய் கண்டறிதல்',
    'Upload a photo to diagnose plant diseases instantly.': 'தாவர நோய்களை உடனடியாகக் கண்டறிய புகைப்படத்தைப் பதிவேற்றவும்.',
    'Market Analysis': 'சந்தை பகுப்பாய்வு',
    'Analyze market trends and prices for your crops.': 'உங்கள் பயிர்களுக்கான சந்தை நிலவரங்கள் மற்றும் விலைகளை பகுப்பாய்வு செய்யுங்கள்.',
    'Sustainability Score': 'நிலைத்தன்மை மதிப்பெண்',
    'Calculate and improve your farm’s sustainability rating.': 'உங்கள் பண்ணையின் நிலைத்தன்மை மதிப்பீட்டைக் கணக்கிட்டு மேம்படுத்தவும்.',
    'Community Forum': 'சமூக மன்றம்',
    'Connect with other farmers, ask questions, and share knowledge.': 'பிற விவசாயிகளுடன் இணையுங்கள், கேள்விகள் கேளுங்கள் மற்றும் அறிவைப் பகிர்ந்து கொள்ளுங்கள்.',
    'Achievements': 'சாதனைகள்',
    'Track your progress and earn badges for your farming skills.': 'உங்கள் முன்னேற்றத்தைக் கண்காணித்து, உங்கள் விவசாய திறன்களுக்கான பேட்ஜ்களைப் பெறுங்கள்.',
    'Dashboard': 'டாஷ்போர்டு',
    'Crop Recommendation': 'பயிர் பரிந்துரை',
    'Disease Detection': 'நோய் கண்டறிதல்',
    'Educational Modules': 'கல்வி தொகுதிகள்',
    'Point of Sale': 'விற்பனை புள்ளி',
    'Products': 'தயாரிப்புகள்',
    'Sales History': 'விற்பனை வரலாறு',

    // Crop Rec Page
    'Enter coordinates manually or use your GPS to fetch soil data. Then, describe your farm, and our AI will suggest the best crops for you.': 'மண் தரவுகளைப் பெற ஆயங்களை கைமுறையாக உள்ளிடவும் அல்லது உங்கள் GPS-ஐப் பயன்படுத்தவும். பின்னர், உங்கள் பண்ணையை விவரிக்கவும், எங்கள் AI உங்களுக்கான சிறந்த பயிர்களைப் பரிந்துரைக்கும்.',
    '1. Location for Soil Analysis': '1. மண் ஆய்வுக்கான இடம்',
    'Latitude (e.g., 23.610)': 'அட்சரேகை (எ.கா., 23.610)',
    'Longitude (e.g., 85.279)': 'தீர்க்கரேகை (எ.கா., 85.279)',
    'Fetch Data for Coordinates': 'ஆயங்களுக்கான தரவைப் பெறவும்',
    'Detect My Location & Fetch Data': 'என் இருப்பிடத்தைக் கண்டறிந்து தரவைப் பெறவும்',
    'The AI will use the fetched soil data as its primary source for recommendations.': 'AI பரிந்துரைகளுக்கான முதன்மை ஆதாரமாகப் பெறப்பட்ட மண் தரவைப் பயன்படுத்தும்.',
    '2. Farm & Climate Details': '2. பண்ணை மற்றும் காலநிலை விவரங்கள்',
    'Annual Rainfall': 'ஆண்டு மழைப்பொழிவு',
    'Primary Soil Type': 'முதன்மை மண் வகை',
    'Primary Goal': 'முதன்மை குறிக்கோள்',
    'Risk Tolerance': 'இடர் சகிப்புத்தன்மை',
    'Field Size': 'நிலத்தின் அளவு',
    'Total Budget (₹)': 'மொத்த பட்ஜெட் (₹)',
    'Total Budget (e.g., 50000)': 'மொத்த பட்ஜெட் (எ.கா., 50000)',
    'Fertilizer Preference': 'உரம் விருப்பம்',
    'Irrigation Method': 'நீர்ப்பாசன முறை',
    'Crop History': 'பயிர் வரலாறு',
    'Most Recent Crop': 'சமீபத்திய பயிர்',
    'Harvest Year': 'அறுவடை ஆண்டு',
    'What was the most recent crop grown on this field?': 'இந்த நிலத்தில் பயிரிடப்பட்ட மிகச் சமீபத்திய பயிர் என்ன?',
    'Recommend Crops': 'பயிர்களைப் பரிந்துரைக்கவும்',
    'AI-Powered Recommendations': 'AI-ஆற்றல் பரிந்துரைகள்',
    'Based on your input, here are our top suggestions.': 'உங்கள் உள்ளீட்டின் அடிப்படையில், இதோ எங்களின் சிறந்த பரிந்துரைகள்.',
    'SoilGrids Data Preview': 'SoilGrids தரவு முன்னோட்டம்',
    "This is the scientific soil data fetched from SoilGrids.org for your location. Review the data and visual maps. Click 'Use This Data' when done.": "இது SoilGrids.org இலிருந்து உங்கள் இடத்திற்காகப் பெறப்பட்ட அறிவியல் மண் தரவு. தரவு மற்றும் வரைபடங்களைச் சரிபார்க்கவும். முடிந்ததும் 'இந்தத் தரவைப் பயன்படுத்து' என்பதைக் கிளிக் செய்யவும்.",
    'Table Data': 'அட்டவணை தரவு',
    'Interactive Map': 'ஊடாடும் வரைபடம்',
    'Raw Data': 'மூலத் தரவு',
    'View on Google Maps': 'Google வரைபடத்தில் பார்க்கவும்',
    'Use This Data': 'இந்தத் தரவைப் பயன்படுத்தவும்',
    'Cancel': 'ரத்துசெய்',
    'Our AI is analyzing your farm data...': 'எங்கள் AI உங்கள் பண்ணை தரவை ஆய்வு செய்கிறது...',
    'Recommended Crops': 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    'Reasoning': 'காரணம்',
    'Your Recommendations Await': 'உங்கள் பரிந்துரைகள் காத்திருக்கின்றன',
    'totalBudgetPlaceholder': 'எ.கா., 50000',
    'latitudePlaceholder': 'அட்சரேகை (எ.கா., 23.610)',
    'longitudePlaceholder': 'தீர்க்கரேகை (எ.கா., 85.279)',
    'fertilizerPrefLabel': 'உரம் விருப்பம்',
    'irrigationMethodLabel': 'நீர்ப்பாசன முறை',
    'harvestYearLabel': 'அறுவடை ஆண்டு',
    'resultTitle': 'AI-ஆற்றல் பரிந்துரைகள்',
    'resultDescription': 'உங்கள் உள்ளீட்டின் அடிப்படையில், இதோ எங்களின் சிறந்த பரிந்துரைகள்.',
    'soilDialogTitle': 'SoilGrids தரவு முன்னோட்டம்',
    'soilDialogDescription': "இது SoilGrids.org இலிருந்து உங்கள் இடத்திற்காகப் பெறப்பட்ட அறிவியல் மண் தரவு. தரவு மற்றும் வரைபடங்களைச் சரிபார்க்கவும். முடிந்ததும் 'இந்தத் தரவைப் பயன்படுத்து' என்பதைக் கிளிக் செய்யவும்.",
    'tableTab': 'அட்டவணை தரவு',
    'mapsTab': 'ஊடாடும் வரைபடம்',
    'rawTab': 'மூலத் தரவு',
    'googleMapsButton': 'Google வரைபடத்தில் பார்க்கவும்',
    'useDataButton': 'இந்தத் தரவைப் பயன்படுத்தவும்',
    'cancelButton': 'ரத்துசெய்',
    'placeholderDescription': 'எங்கள் AI உங்கள் பண்ணை தரவை ஆய்வு செய்கிறது...',
    'recommendedCropsLabel': 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    'reasoningLabel': 'காரணம்',
    'placeholderTitle': 'உங்கள் பரிந்துரைகள் காத்திருக்கின்றன',
    'farmDetailsLabel': 'பண்ணை மற்றும் காலநிலை விவரங்கள்',
    'annualRainfallLabel': 'ஆண்டு மழைப்பொழிவு',
    'soilTypeLabel': 'முதன்மை மண் வகை',
    'primaryGoalLabel': 'முதன்மை குறிக்கோள்',
    'riskToleranceLabel': 'இடர் சகிப்புத்தன்மை',
    'fieldSizeLabel': 'நிலத்தின் அளவு',
    'totalBudgetLabel': 'மொத்த பட்ஜெட் (₹)',
    'recentCropLabel': 'சமீபத்திய பயிர்',
    'cropHistoryDescription': 'இந்த நிலத்தில் பயிரிடப்பட்ட மிகச் சமீபத்திய பயிர் என்ன?',
    'locationDescription': 'AI பரிந்துரைகளுக்கான முதன்மை ஆதாரமாகப் பெறப்பட்ட மண் தரவைப் பயன்படுத்தும்.',
    'detectLocationButton': 'என் இருப்பிடத்தைக் கண்டறிந்து தரவைப் பெறவும்',
    'fetchCoordsButton': 'ஆயங்களுக்கான தரவைப் பெறவும்',
    'locationLabel': 'மண் ஆய்வுக்கான இடம்',
    'description': 'மண் தரவுகளைப் பெற ஆயங்களை கைமுறையாக உள்ளிடவும் அல்லது உங்கள் GPS-ஐப் பயன்படுத்தவும். பின்னர், உங்கள் பண்ணையை விவரிக்கவும், எங்கள் AI உங்களுக்கான சிறந்த பயிர்களைப் பரிந்துரைக்கும்.',
    'title': 'AI பயிர் பரிந்துரை',
    'cropHistoryLabel': 'பயிர் வரலாறு',

    // Disease Detection

    "Use your camera or upload a photo of an affected plant leaf to get an AI-powered diagnosis.": "பாதிக்கப்பட்ட தாவர இலையின் புகைப்படத்தை பதிவேற்றவும் அல்லது கேமராவைப் பயன்படுத்தி AI-மூலம் நோயறிதலைப் பெறவும்.",
    "Live Camera": "நேரடி கேமரா",
    "Upload File": "கோப்பைப் பதிவேற்றவும்",
    "Camera Access Required": "கேமரா அணுகல் தேவை",
    "Please allow camera access in your browser settings to use this feature.": "இந்த அம்சத்தைப் பயன்படுத்த உங்கள் உலாவி அமைப்புகளில் கேமரா அணுகலை அனுமதிக்கவும்.",
    "Capture & Diagnose": "படம் பிடித்து கண்டறிதல்",
    "Plant Photo": "தாவர புகைப்படம்",
    "Upload a clear image of the affected plant part. Max 5MB.": "பாதிக்கப்பட்ட தாவரப் பகுதியின் தெளிவான படத்தை பதிவேற்றவும். அதிகபட்சம் 5MB.",
    "Diagnose": "கண்டறிதல்",
    "Image to Analyze": "பகுப்பாய்வுக்கான படம்",
    "Scanning for diseases...": "நோய்களுக்காக ஸ்கேன் செய்கிறது...",
    "Diagnosis Result": "கண்டறிதல் முடிவு",
    "Confidence": "நம்பிக்கை",
    "Description & Treatment": "விளக்கம் மற்றும் சிகிச்சை",
    "Looks Healthy!": "ஆரோக்கியமாகத் தெரிகிறது!",
    "No significant disease was detected in the image.": "படத்தில் குறிப்பிடத்தக்க நோய் ஏதும் கண்டறியப்படவில்லை.",
    "Use your camera or upload an image and your diagnosis will appear here.": "உங்கள் கேமராவைப் பயன்படுத்தவும் அல்லது ஒரு படத்தைப் பதிவேற்றவும், உங்கள் நோயறிதல் இங்கே தோன்றும்.",

    // Market Analysis
    "Market Price Visualization": "சந்தை விலை காட்சிப்படுத்தல்",
    "Select filters to see live price trends from Agmarknet for a crop in your market.": "உங்கள் சந்தையில் ஒரு பயிருக்கான நேரடி விலை நிலவரங்களை Agmarknet-லிருந்து பார்க்க வடிப்பான்களைத் தேர்ந்தெடுக்கவும்.",
    "Select Commodity": "பொருளைத் தேர்ந்தெடுக்கவும்",
    "Select State": "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    "Select District": "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    "Enter Market Name": "சந்தை பெயரை உள்ளிடவும்",
    "From Date": "தேதி முதல்",
    "To Date": "தேதி வரை",
    "Clear All Filters": "வடிப்பான்களை அழிக்கவும்",
    "Using Sample Data": "மாதிரித் தரவைப் பயன்படுத்துகிறது",
    "Live data from Agmarknet is currently unavailable. Displaying sample data instead.": "Agmarknet-லிருந்து நேரடித் தரவு தற்போது கிடைக்கவில்லை. அதற்குப் பதிலாக மாதிரித் தரவு காட்டப்படுகிறது.",
    "Could Not Fetch Data": "தரவைப் பெற முடியவில்லை",
    "No market data found for this crop/region.": "இந்தப் பயிர்/பகுதிக்கு சந்தைத் தரவு எதுவும் கிடைக்கவில்லை.",
    "Please select filters to view price data from Agmarknet.": "Agmarknet-லிருந்து விலை தரவைப் பார்க்க தயவுசெய்து வடிப்பான்களைத் தேர்ந்தெடுக்கவும்.",
    "Generate Market & Profit Analysis": "சந்தை மற்றும் லாபப் பகுப்பாய்வை உருவாக்கு",
    "Filter for market data above, then add your costs to get an AI-powered financial summary.": "மேலே உள்ள சந்தைத் தரவை வடிகட்டவும், பின்னர் உங்கள் செலவுகளைச் சேர்த்து AI-ஆற்றல் நிதிச் சுருக்கத்தைப் பெறவும்.",
    "Market Data (per Ton)": "சந்தை தரவு (டன்னுக்கு)",
    "This will be auto-filled with data from the chart above. You can also paste your own.": "இது மேலே உள்ள விளக்கப்படத்திலிருந்து தரவுகளால் தானாக நிரப்பப்படும். நீங்கள் சொந்தமாகவும் ஒட்டலாம்.",
    "Your Expenditures": "உங்கள் செலவுகள்",
    "e.g., Seeds: ₹2000, Fertilizer: ₹3500, Labor: ₹5000": "எ.கா., விதைகள்: ₹2000, உரம்: ₹3500, கூலி: ₹5000",
    "Analyze Now": "இப்போது பகுப்பாய்வு செய்",
    "Generating analysis...": "பகுப்பாய்வு உருவாகிறது...",
    "AI-Generated Analysis": "AI-உருவாக்கிய பகுப்பாய்வு",
    "Market Summary": "சந்தை சுருக்கம்",
    "Profit & Loss Analysis": "லாப நஷ்ட பகுப்பாய்வு",
    "Your market analysis and profit/loss summary will appear here.": "உங்கள் சந்தை பகுப்பாய்வு மற்றும் லாப/நஷ்ட சுருக்கம் இங்கே தோன்றும்.",
    "Using Dummy Data": "டம்மித் தரவைப் பயன்படுத்துகிறது",
    "Live API keys for Agmarknet are not configured. Displaying dummy data instead.": "Agmarknet-க்கான நேரடி API விசைகள் கட்டமைக்கப்படவில்லை. அதற்குப் பதிலாக டம்மித் தரவு காட்டப்படுகிறது.",

    // Sustainability Score
    "Provide details about your farm to get an AI-calculated sustainability rating.": "AI-கணக்கிடப்பட்ட நிலைத்தன்மை மதிப்பீட்டைப் பெற உங்கள் பண்ணை பற்றிய விவரங்களை வழங்கவும்.",
    "Soil Health": "மண் வளம்",
    "Nitrogen (kg/ha)": "நைட்ரஜன் (கிகி/ஹெக்)",
    "Phosphorus (kg/ha)": "பாஸ்பரஸ் (கிகி/ஹெக்)",
    "Potassium (kg/ha)": "பொட்டாசியம் (கிகி/ஹெக்)",
    "Soil pH": "மண் pH",
    "Moisture (%)": "ஈப்பதம் (%)",
    "Farming Practices": "விவசாய முறைகள்",
    "Irrigation": "நீர்ப்பாசனம்",
    "Tillage": "உழவு",
    "Pesticides": "பூச்சிக்கொல்லிகள்",
    "Crop History & Rotation": "பயிர் வரலாறு & சுழற்சி",
    "Describe your rotation for the last 2-3 seasons.": "கடந்த 2-3 பருவங்களுக்கு உங்கள் பயிர் சுழற்சியை விவரிக்கவும்.",
    "Market & Financials": "சந்தை & நிதி",
    "Describe price trends and your costs.": "விலை நிலவரங்கள் மற்றும் உங்கள் செலவுகளை விவரிக்கவும்.",
    "Calculate Score": "மதிப்பெண்ணைக் கணக்கிடு",
    "Calculating your score...": "உங்கள் மதிப்பெண் கணக்கிடப்படுகிறது...",
    "Your Sustainability Score": "உங்கள் நிலைத்தன்மை மதிப்பெண்",
    "out of 100": "100-க்கு",
    "Rationale & Recommendations": "காரணம் & பரிந்துரைகள்",
    "Your sustainability score and insights will appear here.": "உங்கள் நிலைத்தன்மை மதிப்பெண் மற்றும் நுண்ணறிவு இங்கே தோன்றும்.",

    // Community Forum
    "Connect with farmers, share, and learn.": "விவசாயிகளுடன் இணையுங்கள், பகிருங்கள் மற்றும் கற்றுக்கொள்ளுங்கள்.",
    "Start New Discussion": "புதிய விவாதத்தைத் தொடங்குங்கள்",
    "replies": "பதில்கள்",
    "likes": "விருப்பங்கள்",
    "Back to Forum": "மன்றத்திற்குத் திரும்பு",
    "Posted by": "பதிவிட்டவர்",
    "Like": "விருப்பம்",
    "Replies": "பதில்கள்",
    "Share": "பகிர்",
    "Post a Reply": "பதிலைப் பதிவு செய்",
    "Write your reply here...": "உங்கள் பதிலை இங்கே எழுதுங்கள்...",
    "Submit Reply": "பதிலைச் சமர்ப்பி",

    // Profile
    "Farmer": "விவசாயி",
    "Edit Profile": "சுயவிவரத்தைத் திருத்து",
    "Save Changes": "மாற்றங்களைச் சேமி",

    "About": "பற்றி",
    "Details": "விவரங்கள்",
    "Farming since": "விவசாயம் தொடங்கியது",
    "farm size": "பண்ணை அளவு",
    "Primary Crops": "முதன்மை பயிர்கள்",
    "The main crops cultivated on the farm.": "பண்ணையில் பயிரிடப்படும் முக்கிய பயிர்கள்.",
    "Enter crops separated by commas.": "பயிர்களை கமாவால் பிரித்து உள்ளிடவும்.",
    "Interests": "ஆர்வம்",
    "Topics and techniques of interest.": "ஆர்வமுள்ள தலைப்புகள் மற்றும் நுட்பங்கள்.",
    "Enter interests separated by commas.": "ஆர்வங்களை கமாவால் பிரித்து உள்ளிடவும்.",

    // Achievements
    "Track your progress, earn badges, and become a top farmer!": "உங்கள் முன்னேற்றத்தைக் கண்காணித்து, பேட்ஜ்களைப் பெற்று, சிறந்த விவசாயியாகுங்கள்!",
    "My Badges": "என் பேட்ஜ்கள்",
    "Work in Progress": "வேலை நடந்து கொண்டிருக்கிறது",
    "Leaderboard": "முன்னிலை பலகை",
    "Rank": "தரம்",
    "Score": "மதிப்பெண்",
    "Keep up the great work!": "சிறப்பாகச் செயல்படுங்கள்!",
    "Top 5 farmers by Sustainability Score": "நிலைத்தன்மை மதிப்பெண் அடிப்படையில் முதல் 5 விவசாயிகள்",

    // Placeholders
    "This feature is coming soon! Get ready to earn badges and showcase your farming skills.": "இந்த வசதி விரைவில் வரவுள்ளது! பேட்ஜ்களைப் பெறவும் உங்கள் விவசாயத் திறன்களை வெளிப்படுத்தவும் தயாராகுங்கள்.",
    "Our library of tutorials, guides, and quizzes is being curated. Check back soon to expand your farming knowledge.": "எங்கள் பயிற்சிகள், வழிகாட்டிகள் மற்றும் வினாடி வினாக்களின் நூலகம் உருவாக்கப்படுகிறது. உங்கள் விவசாய அறிவை விரிவுபடுத்த விரைவில் மீண்டும் பார்க்கவும்.",

    // Chatbot
    "Chat with AI": "AI-உடன் பேசுங்கள்",
    "CropNavi Assistant": "CropNavi உதவியாளர்",
    "Online": "ஆன்லைன்",
    "Hello! I'm the CropNavi Assistant. How can I help you today?": "வணக்கம்! நான் CropNavi உதவியாளர். இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    "Ask a question...": "கேள்வியைக் கேளுங்கள்...",

    // Weather Card
    "Weather Intelligence": "வானிலை நுண்ணறிவு",
    "Current Temperature": "தற்போதைய வெப்பநிலை",
    "Humidity": "ஈரப்பதம்",
    "Wind": "காற்று",
    "Rainfall": "மழைப்பொழிவு",
    "Now": "இப்போது",
    "Last 7 Days": "கடந்த 7 நாட்கள்",
    "Last 30 Days": "கடந்த 30 நாட்கள்",
    "Last 6 Months": "கடந்த 6 மாதங்கள்",
    "Last Year": "கடந்த வருடம்",
    "Min": "குறைந்தபட்ச",
    "Max": "அதிகபட்ச",
    "Avg": "சராசரி",
    "Rain": "மழை",
    "weatherDescription": "கோயம்புத்தூர், தமிழ்நாடு",
    "Your Location": "உங்கள் இருப்பிடம்",
    "mapOverlayLabel": "வரைபட அடுக்கு",
    "overlayNone": "ஏதுமில்லை",
    "overlayPh": "pH (நீர்)",
    "overlayClay": "களிமண் அளவு",
    "overlayNitrogen": "நைட்ரஜன்",
    "overlaySoc": "மண் கரிம கார்பன்",
    "overlaySand": "மணல் அளவு",
    "overlaySilt": "வண்டல் மண் அளவு",

    // POS & Products
    'Search products...': 'தயாரிப்புகளைத் தேடுங்கள்...',
    'Add': 'சேர்',
    'Cart': 'கூடை',
    'Customer Name (optional)': 'வாடிக்கையாளர் பெயர் (விருப்ப)',
    'Remove': 'நீக்கு',
    'Total': 'மொத்தம்',
    'Process Sale': 'விற்பனையை செயல்படுத்து',
    'Stock': 'இருப்பு',
    'Insufficient stock': 'போதுமான இருப்பு இல்லை',
    'Cart is empty': 'கூடை காலியாக உள்ளது',
    'Sale processed successfully': 'விற்பனை வெற்றிகரமாக முடிந்தது',
    'Failed to fetch products': 'தயாரிப்புகளைப் பெற முடியவில்லை',
    'Failed to process sale': 'விற்பனையைச் செயல்படுத்த முடியவில்லை',
    'Product Management': 'தயாரிப்பு மேலாண்மை',
    'Edit Product': 'தயாரிப்பைத் திருத்து',
    'Add New Product': 'புதிய தயாரிப்பைச் சேர்',
    'Product Name': 'தயாரிப்பு பெயர்',
    'Description': 'விளக்கம்',
    'Price': 'விலை',
    'Stock Quantity': 'இருப்பு அளவு',
    'Select Category': 'வகையைத் தேர்ந்தெடு',
    'Update': 'புதுப்பி',
    'Create': 'உருவாக்கு',
    'Edit': 'திருத்து',
    'Delete': 'நீக்கு',
    'Failed to fetch categories': 'வகைகளைப் பெற முடியவில்லை',
    'Product updated successfully': 'தயாரிப்பு புதுப்பிக்கப்பட்டது',
    'Product created successfully': 'தயாரிப்பு உருவாக்கப்பட்டது',
    'Failed to save product': 'தயாரிப்பைச் சேமிக்க முடியவில்லை',
    'Are you sure you want to delete this product?': 'இந்தத் தயாரிப்பை நிச்சயம் நீக்க விரும்புகிறீர்களா?',
    'Product deleted successfully': 'தயாரிப்பு நீக்கப்பட்டது',
    'Failed to delete product': 'தயாரிப்பை நீக்க முடியவில்லை',

    // Sales
    'Search sales...': 'விற்பனையைத் தேடு...',
    'Sale #': 'விற்பனை #',
    'No notes': 'குறிப்புகள் இல்லை',
    'items': 'பொருட்கள்',
    'Sale Details': 'விற்பனை விவரங்கள்',
    'Date': 'தேதி',
    'Notes': 'குறிப்புகள்',
    'Items': 'பொருட்கள்',
    'Select a sale to view details': 'விவரங்களைக் காண விற்பனையைத் தேர்ந்தெடு',
    'Failed to fetch sales': 'விற்பனை விவரங்களைப் பெற முடியவில்லை',
    'None': 'எதுவுமில்லை',
    'All': 'அனைத்தும்',
    'Receipt': 'ரசீது',
    'Sale Complete': 'விற்பனை முடிந்தது',
    'Subtotal': 'கூட்டுத்தொகை',
    'Close': 'மூடு',
    'Clear Cart': 'கூடையை அழி',
    'Transaction ID': 'பரிவர்த்தனை ஐடி',
    'Stock Limit': 'சரக்கு வரம்பு',
    'Actions': 'செயல்கள்',
    'View Details': 'விவரங்களைப் பார்',
    'Manage sales and inventory efficiently': 'விற்பனை மற்றும் இருப்பை திறம்பட நிர்வகிக்கவும்',
    'No products found': 'தயாரிப்புகள் ஏதும் இல்லை',
  }
};



export async function translatePageContent(
  input: TranslatePageContentInput
): Promise<TranslatePageContentOutput> {

  const lang = input.targetLanguage.toLowerCase().split(' ')[0];
  const dictionary = translationsDb[lang] || {};

  // Dummy implementation: uses the dictionary and returns original text if not found.
  const dummyTranslations = input.texts.map(text => {
    return dictionary[text] || text;
  });

  // Simulate a network delay
  await new Promise(resolve => setTimeout(resolve, 500));

  return {
    translations: dummyTranslations,
  };
}

const translatePageContentFlow = ai.defineFlow(
  {
    name: 'translatePageContentFlow',
    inputSchema: TranslatePageContentInputSchema,
    outputSchema: TranslatePageContentOutputSchema,
  },
  translatePageContent
);


